/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html", "./*.js"],
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "on-primary-container": "#8ee4a6",
                    "error": "#ba1a1a",
                    "error-container": "#ffdad6",
                    "primary-fixed": "#9ef6b6",
                    "outline-variant": "#bec9be",
                    "background": "#f9f9ff",
                    "on-surface-variant": "#3f4940",
                    "on-error-container": "#93000a",
                    "on-tertiary-fixed-variant": "#454747",
                    "on-secondary": "#ffffff",
                    "on-primary-fixed-variant": "#00522a",
                    "inverse-surface": "#273140",
                    "on-error": "#ffffff",
                    "on-tertiary-container": "#d1d1d1",
                    "on-primary-fixed": "#00210e",
                    "secondary-fixed-dim": "#c5c6c8",
                    "surface-container-highest": "#d9e3f7",
                    "tertiary-fixed": "#e2e2e2",
                    "secondary-container": "#dee0e2",
                    "inverse-on-surface": "#ebf1ff",
                    "on-surface": "#121c2a",
                    "primary-container": "#006837",
                    "inverse-primary": "#83d99c",
                    "surface-tint": "#0b6d3b",
                    "surface-container-high": "#dee9fd",
                    "tertiary": "#414343",
                    "surface-container-low": "#eff3ff",
                    "surface-bright": "#f9f9ff",
                    "tertiary-fixed-dim": "#c6c6c7",
                    "on-secondary-container": "#606365",
                    "primary": "#004d27",
                    "on-secondary-fixed-variant": "#444749",
                    "surface-variant": "#d9e3f7",
                    "surface-dim": "#d0daef",
                    "surface": "#f9f9ff",
                    "surface-container": "#e6eeff",
                    "tertiary-container": "#585a5a",
                    "secondary-fixed": "#e1e2e4",
                    "on-primary": "#ffffff",
                    "surface-container-lowest": "#ffffff",
                    "on-tertiary-fixed": "#1a1c1c",
                    "outline": "#6f7a70",
                    "on-tertiary": "#ffffff",
                    "on-secondary-fixed": "#191c1e",
                    "on-background": "#121c2a",
                    "secondary": "#5c5f60",
                    "primary-fixed-dim": "#83d99c"
            },
            "borderRadius": {
                    "DEFAULT": "0.25rem",
                    "lg": "0.5rem",
                    "xl": "0.75rem",
                    "full": "9999px",
                    "2xl": "1rem"
            },
            "spacing": {
                    "margin-mobile": "16px",
                    "margin-desktop": "32px",
                    "gutter": "24px",
                    "card-padding": "24px",
                    "stack-gap": "16px",
                    "base": "4px"
            },
            "fontFamily": {
                    "title-md": ["Hanken Grotesk"],
                    "headline-lg": ["Hanken Grotesk"],
                    "display-lg": ["Hanken Grotesk"],
                    "headline-lg-mobile": ["Hanken Grotesk"],
                    "body-lg": ["Hanken Grotesk"],
                    "label-caps": ["Inter"],
                    "body-sm": ["Hanken Grotesk"]
            },
            "fontSize": {
                    "title-md": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
                    "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
                    "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                    "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                    "body-lg": ["16px", {"lineHeight": "26px", "fontWeight": "400"}],
                    "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700"}],
                    "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
            }
          },
        },
      };